"""add business_analysis, decision_log, legacy_analysis_boxes

Revision ID: 16be052ef204
Revises: 6c9a44157749
Create Date: 2026-09-05 15:05:07.785636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16be052ef204'
down_revision: Union[str, Sequence[str], None] = '6c9a44157749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_analysis',
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('idea_business', sa.String(), nullable=False),
    sa.Column('idea_problem', sa.String(), nullable=False),
    sa.Column('idea_customer', sa.String(), nullable=False),
    sa.Column('idea_goal', sa.String(), nullable=False),
    sa.Column('an_market', sa.String(), nullable=False),
    sa.Column('an_competition', sa.String(), nullable=False),
    sa.Column('an_strength', sa.String(), nullable=False),
    sa.Column('an_risk', sa.String(), nullable=False),
    sa.Column('fin_investment', sa.String(), nullable=False),
    sa.Column('fin_cost', sa.String(), nullable=False),
    sa.Column('fin_revenue', sa.String(), nullable=False),
    sa.Column('fin_profit', sa.String(), nullable=False),
    sa.Column('decision_why', sa.String(), nullable=False),
    sa.Column('decision_status', sa.String(), nullable=False),
    sa.Column('next_action', sa.String(), nullable=False),
    sa.Column('next_priority', sa.String(), nullable=False),
    sa.Column('next_deadline', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('project_key')
    )
    op.create_table('decision_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('why', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legacy_analysis_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('box_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_key', 'box_index', name='uq_project_box')
    )
    # ### end Alembic commands ###

    # One empty BusinessAnalysis row per fixed project slot, matching
    # how the projects/habits tables are pre-seeded rather than
    # created lazily on first edit.
    ba_table = sa.table(
        'business_analysis',
        sa.column('project_key', sa.String),
        sa.column('idea_business', sa.String),
        sa.column('idea_problem', sa.String),
        sa.column('idea_customer', sa.String),
        sa.column('idea_goal', sa.String),
        sa.column('an_market', sa.String),
        sa.column('an_competition', sa.String),
        sa.column('an_strength', sa.String),
        sa.column('an_risk', sa.String),
        sa.column('fin_investment', sa.String),
        sa.column('fin_cost', sa.String),
        sa.column('fin_revenue', sa.String),
        sa.column('fin_profit', sa.String),
        sa.column('decision_why', sa.String),
        sa.column('decision_status', sa.String),
        sa.column('next_action', sa.String),
        sa.column('next_priority', sa.String),
        sa.column('next_deadline', sa.String),
    )
    op.bulk_insert(ba_table, [
        {
            "project_key": key,
            "idea_business": "", "idea_problem": "", "idea_customer": "", "idea_goal": "",
            "an_market": "", "an_competition": "", "an_strength": "", "an_risk": "",
            "fin_investment": "", "fin_cost": "", "fin_revenue": "", "fin_profit": "",
            "decision_why": "", "decision_status": "",
            "next_action": "", "next_priority": "", "next_deadline": "",
        }
        for key in ("proj1", "proj2", "proj3", "proj4", "proj5", "proj6")
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legacy_analysis_boxes')
    op.drop_table('decision_log')
    op.drop_table('business_analysis')
    # ### end Alembic commands ###
