"""create tasks table

Revision ID: 5fe711c4b0e2
Revises: 
Create Date: 2026-09-05 13:00:57.065747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe711c4b0e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('list_key', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('secs', sa.Float(), nullable=False),
    sa.Column('sessions', sa.JSON(), nullable=False),
    sa.Column('est', sa.Integer(), nullable=False),
    sa.Column('mit', sa.Boolean(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('strike', sa.Boolean(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('psrc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
