"""add projects, project_subtasks, project_activity, circle_people

Revision ID: 6c9a44157749
Revises: 8ebdffef9b2e
Create Date: 2026-09-05 14:21:22.351672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9a44157749'
down_revision: Union[str, Sequence[str], None] = '8ebdffef9b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('accent_color', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('detail_note', sa.String(), nullable=False),
    sa.Column('note_bg', sa.String(), nullable=True),
    sa.Column('note_fg', sa.String(), nullable=True),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('running_since', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('circle_people',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('project_key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cadence_days', sa.Integer(), nullable=False),
    sa.Column('last_contact', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('secs', sa.Float(), nullable=False),
    sa.Column('manual_mark', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_key', 'day', name='uq_project_day')
    )
    op.create_table('project_subtasks',
    sa.Column('pid', sa.String(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('added_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    # SQLite has no ALTER TABLE ADD CONSTRAINT — batch mode recreates the
    # table under the hood instead, which is required here.
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_tasks_project', 'projects', ['project'], ['key'])
        batch_op.create_foreign_key('fk_tasks_psrc', 'project_subtasks', ['psrc'], ['pid'])
    # ### end Alembic commands ###

    projects_table = sa.table(
        'projects',
        sa.column('key', sa.String),
        sa.column('name', sa.String),
        sa.column('accent_color', sa.String),
        sa.column('note', sa.String),
        sa.column('detail_note', sa.String),
        sa.column('target_minutes', sa.Integer),
    )
    op.bulk_insert(projects_table, [
        {"key": "proj1", "name": "", "accent_color": "#0550AE",
         "note": "", "detail_note": "", "target_minutes": 60},
        {"key": "proj2", "name": "", "accent_color": "#BC4C00",
         "note": "", "detail_note": "", "target_minutes": 60},
        {"key": "proj3", "name": "", "accent_color": "#1A7F37",
         "note": "", "detail_note": "", "target_minutes": 60},
        {"key": "proj4", "name": "", "accent_color": "#0969DA",
         "note": "", "detail_note": "", "target_minutes": 60},
        {"key": "proj5", "name": "", "accent_color": "#0E7490",
         "note": "", "detail_note": "", "target_minutes": 60},
        {"key": "proj6", "name": "", "accent_color": "#6639BA",
         "note": "", "detail_note": "", "target_minutes": 60},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_project', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_psrc', type_='foreignkey')
    op.drop_table('project_subtasks')
    op.drop_table('project_activity')
    op.drop_table('circle_people')
    op.drop_table('projects')
    # ### end Alembic commands ###
