"""add goals table and goal fields to app_state

Revision ID: 6cf6bdf5f418
Revises: dcf3914a6fcc
Create Date: 2026-09-05 22:43:20.963110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf6bdf5f418'
down_revision: Union[str, Sequence[str], None] = 'dcf3914a6fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('done_date', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default needed: the app_state singleton row already exists
    # in every installed DB, and SQLite can't add a NOT NULL column
    # without a default to backfill it.
    op.add_column('app_state', sa.Column('goal_project', sa.String(), nullable=False, server_default='proj1'))
    op.add_column('app_state', sa.Column('sec_title_yearly', sa.String(), nullable=True))
    op.add_column('app_state', sa.Column('sec_title_monthly', sa.String(), nullable=True))
    op.add_column('app_state', sa.Column('sec_title_weekly', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_state', 'sec_title_weekly')
    op.drop_column('app_state', 'sec_title_monthly')
    op.drop_column('app_state', 'sec_title_yearly')
    op.drop_column('app_state', 'goal_project')
    op.drop_table('goals')
    # ### end Alembic commands ###
