"""add task_day_view to app_state

Revision ID: 741ae20ebaf7
Revises: f9d3449bef17
Create Date: 2026-09-05 18:05:48.277268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741ae20ebaf7'
down_revision: Union[str, Sequence[str], None] = 'f9d3449bef17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'app_state',
        sa.Column('task_day_view', sa.String(), nullable=False, server_default='today'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_state', 'task_day_view')
    # ### end Alembic commands ###
