"""add habits, habit_completions, daily_intentions

Revision ID: 8ebdffef9b2e
Revises: 5fe711c4b0e2
Create Date: 2026-09-05 13:49:59.175170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ebdffef9b2e'
down_revision: Union[str, Sequence[str], None] = '5fe711c4b0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_intentions',
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'day', name='uq_habit_day')
    )
    # ### end Alembic commands ###

    # Seed the same starting habit set the legacy Tkinter app shipped
    # (_HABIT_DEFAULTS), so a fresh install looks the same as before.
    habits_table = sa.table(
        'habits',
        sa.column('category', sa.String),
        sa.column('name', sa.String),
        sa.column('sort_order', sa.Integer),
        sa.column('active', sa.Boolean),
    )
    defaults = {
        "money": ["Review finances", "Work on income", "Track expenses",
                  "Learn business skill", "Network"],
        "health": ["Exercise 30min", "Sleep 7-8h", "Drink 2L water",
                   "Healthy meal", "No junk food"],
        "relation": ["Family time", "Help someone", "Gratitude",
                     "No negative talk", "Mentor/learn"],
        "mind": ["Read 30min", "Meditate 10min", "Journal",
                 "Learn new thing", "No social media 1h"],
    }
    op.bulk_insert(habits_table, [
        {"category": cat, "name": name, "sort_order": i, "active": True}
        for cat, names in defaults.items()
        for i, name in enumerate(names)
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_completions')
    op.drop_table('habits')
    op.drop_table('daily_intentions')
    # ### end Alembic commands ###
