"""add product journey tables

Revision ID: adba321546dd
Revises: 73c22bb81861
Create Date: 2026-09-06 00:45:38.377718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adba321546dd'
down_revision: Union[str, Sequence[str], None] = '73c22bb81861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_log_entries',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journey_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('gate', sa.String(), nullable=False),
    sa.Column('gate_done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_key', 'stage_index', name='uq_project_stage')
    )
    op.create_table('journey_tasks',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_journey',
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('proj_name', sa.String(), nullable=False),
    sa.Column('tagline', sa.String(), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=False),
    sa.Column('attach_file', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_key'], ['projects.key'], ),
    sa.PrimaryKeyConstraint('project_key')
    )
    # ### end Alembic commands ###

    # One row per fixed project slot / per (project, stage) — same
    # pre-seeded-not-lazily-created pattern as business_analysis and
    # legacy_analysis_boxes. proj_name is seeded empty rather than
    # copied from Project.name at migration time: legacy only copies it
    # once, on first open, as a fallback default — the port's engine
    # layer does that same fallback live on read, so this stays correct
    # even if the project is renamed later.
    PROJECT_KEYS = ("proj1", "proj2", "proj3", "proj4", "proj5", "proj6")
    JOURNEY_STAGES = (
        ("Product Research", "Find the problem and the opportunity"),
        ("Sales Channel Development", "Website / landing page"),
        ("Search Engine Optimization", "Product content / creative"),
        ("Viral Content", "Optimize and prepare"),
        ("Customer Acquisition", "Bring visitors and customers"),
        ("Sales and Feedback", "Revenue, launch, and growth"),
    )

    journey_table = sa.table(
        'project_journey',
        sa.column('project_key', sa.String),
        sa.column('proj_name', sa.String),
        sa.column('tagline', sa.String),
        sa.column('cover_image', sa.String),
        sa.column('attach_file', sa.String),
    )
    op.bulk_insert(journey_table, [
        {
            "project_key": key,
            "proj_name": "",
            "tagline": "Product Idea → Launch",
            "cover_image": "",
            "attach_file": "",
        }
        for key in PROJECT_KEYS
    ])

    stages_table = sa.table(
        'journey_stages',
        sa.column('project_key', sa.String),
        sa.column('stage_index', sa.Integer),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('gate', sa.String),
        sa.column('gate_done', sa.Boolean),
    )
    op.bulk_insert(stages_table, [
        {
            "project_key": key,
            "stage_index": i,
            "name": name,
            "description": desc,
            "gate": "",
            "gate_done": False,
        }
        for key in PROJECT_KEYS
        for i, (name, desc) in enumerate(JOURNEY_STAGES)
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_journey')
    op.drop_table('journey_tasks')
    op.drop_table('journey_stages')
    op.drop_table('journey_log_entries')
    # ### end Alembic commands ###
