"""add theme and onboarded to app_state

Revision ID: dcf3914a6fcc
Revises: 741ae20ebaf7
Create Date: 2026-09-05 18:33:11.700839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf3914a6fcc'
down_revision: Union[str, Sequence[str], None] = '741ae20ebaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'app_state',
        sa.Column('theme', sa.String(), nullable=False, server_default='focus'),
    )
    op.add_column(
        'app_state',
        sa.Column('onboarded', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_state', 'onboarded')
    op.drop_column('app_state', 'theme')
    # ### end Alembic commands ###
