"""add app_state singleton for daily strike reset

Revision ID: f9d3449bef17
Revises: 16be052ef204
Create Date: 2026-09-05 17:42:17.229488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d3449bef17'
down_revision: Union[str, Sequence[str], None] = '16be052ef204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_strike_reset_day', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed the single row up front so callers can always assume it
    # exists (matches how projects/habits are pre-seeded rather than
    # created lazily on first use).
    app_state = sa.table(
        'app_state',
        sa.column('id', sa.Integer),
        sa.column('last_strike_reset_day', sa.String),
    )
    op.bulk_insert(app_state, [{"id": 1, "last_strike_reset_day": None}])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_state')
    # ### end Alembic commands ###
